sudo: false
language: java
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: "true"

before_script:
   - gradle -v
   - chmod +x gradlew

jdk:
- openjdk7
scala:
   - 2.11.2

matrix:
  include:
  - jdk: oraclejdk7
    script: 
        - ./gradle --debug
        - ./gradlew test
  - jdk: oraclejdk8
    script: 
        - ./gradle --debug
        - ./gradlew test

branches:
  only:
  - 0.9.0

after_success:
  - bash <(curl -s https://codecov.io/bash)

