sudo: false
language: java
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: "true"

before_script:
   - gradle -v
   - chmod +x gradlew
   - sudo service postgresql stop || true
   - sudo service mysql stop || true
   - sudo service memcached stop || true
   - sudo service bootlogd stop || true
   - sudo service elasticsearch stop || true
   - sudo service mongodb stop || true
   - sudo service neo4j stop || true
   - sudo service cassandra stop || true
   - sudo service riak stop || true
   - sudo service rsync stop || true
   - sudo service x11-common stop || true

jdk:
  - openjdk7
  - oraclejdk8
scala:
   - 2.10.4
   - 2.11.5

script: 
   - gradle --info
   - ./gradlew --stacktrace --quiet test

branches:
  only:
  - 0.9.0

after_success:
  - bash <(curl -s https://codecov.io/bash)

